<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="7" started-at="2013-01-19T20:28:12Z" finished-at="2013-01-19T20:28:12Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="7" started-at="2013-01-19T20:28:12Z" finished-at="2013-01-19T20:28:12Z">
      <class name="net.binout.codestory2013.HeinRestServiceTest">
        <test-method status="PASS" signature="constructor_should_create_calculator()[pri:0, instance:net.binout.codestory2013.HeinRestServiceTest@5fa16fc7]" name="constructor_should_create_calculator" duration-ms="0" started-at="2013-01-19T21:28:12Z" finished-at="2013-01-19T21:28:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- constructor_should_create_calculator -->
        <test-method status="PASS" signature="constructor_should_create_empty_cache()[pri:0, instance:net.binout.codestory2013.HeinRestServiceTest@5fa16fc7]" name="constructor_should_create_empty_cache" duration-ms="0" started-at="2013-01-19T21:28:12Z" finished-at="2013-01-19T21:28:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- constructor_should_create_empty_cache -->
        <test-method status="PASS" signature="constructor_should_load_enonce()[pri:0, instance:net.binout.codestory2013.HeinRestServiceTest@5fa16fc7]" name="constructor_should_load_enonce" duration-ms="0" started-at="2013-01-19T21:28:12Z" finished-at="2013-01-19T21:28:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- constructor_should_load_enonce -->
        <test-method status="FAIL" signature="postcontruct_should_load_cache()[pri:0, instance:net.binout.codestory2013.HeinRestServiceTest@5fa16fc7]" name="postcontruct_should_load_cache" duration-ms="1" started-at="2013-01-19T21:28:12Z" finished-at="2013-01-19T21:28:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at net.binout.codestory2013.HeinRestServiceTest.postcontruct_should_load_cache(HeinRestServiceTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:54)
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64)
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106)
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcontruct_should_load_cache -->
      </class> <!-- net.binout.codestory2013.HeinRestServiceTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
